export * from './center-branch.repository';
export * from './manager.repository';
export * from './migrations.repository';
export * from './student.repository';
export * from './subjects.repository';
export * from './teacher.repository';
export * from './tuition.repository';
export * from './users.repository';
export * from './user-credentials.repository';
